### ISSUE TITLE
MQTT communication

### ISSUE THREAD

**Issue by TKoe92** [ubilab-escape/second-door#25]
Communicate with the Operator:

- [x] setup WiFi

- [x] setup MQTT

- [x] define global Variables for each puzzle and implement them to skip puzzles if necessary

- [x] draw flow chart for operator group

- [x] setup topics and tx/rx messages

**Comment by JayWiz** [comment]
MQTT still missing entirely for fusebox

**Comment by JayWiz** [comment]
SequenceWorkflow("Solve fusebox", [
                    ActivateLaserWorkflow("Laser_lab_room", "7/laser"),
                    Workflow("Fusebox_lab_room", "7/fusebox/laserDetection"),
                    ParallelWorkflow("Solve fuse box", [
                        Workflow("Fusebox_lab_room", "7/fusebox/rewiring0"),
                        Workflow("Fusebox_lab_room", "7/fusebox/rewiring1"),
                        Workflow("Fusebox_lab_room", "7/fusebox/potentiometer")
                    ]),
                    Workflow("Robot_lab_room", "7/robot")
                ])

**Comment by TKoe92** [comment]
use mqtt_base subrepo for communication
