### ISSUE TITLE
ADC2 not working with WiFi

### ISSUE THREAD

**Issue by JayWiz** [ubilab-escape/second-door#41]
ADC2 cannot be used while using WiFI in a normal way while using Arduino Framework
see: https://github.com/espressif/arduino-esp32/issues/102

**Comment by JayWiz** [comment]
Workaround ATM: Single corresponding bit got new limits to fake a right value at this pin

**Comment by maxim0815** [comment]
solved by leaving out this port. Now 4 wires instead of 5.
